// 리뷰 도구 데이터 — homePro 전 도메인 화면 목록 + 기획 요약.
// seekone 리뷰 도구 이식. 코드 기반 자동 추출본이니 부정확하면 형이 수정.
// 도메인 9개 · 화면 71개.
// 각 화면: { no, id(전역 유니크), name, path(빈 문자열=정책/화면없음), spec:[불릿, ★=핵심] }

export const DOMAINS = [
  { key: 'auth', label: '인증·법률', screens: [
    { no: 'AU-01', id: 'splash', name: '스플래시(진입 분기)', path: '/MobileSplash', spec: [
      '★ watchAuthState로 로그인 상태를 감지해 로그인/닉네임설정/메인으로 자동 분기하는 라우팅 관문',
      '미로그인 시 1.5초 뒤 /MobileLogin으로 replace 이동',
      '프로필이 없거나 name·role 미설정이면 /MobileSetNickname으로 이동',
      '조건 통과 시 UserContext(USERS_ID·USERINFO)를 세팅하고 /MobileMain으로 이동',
      '전화번호 등록 단계는 제거되어 닉네임·역할만 있으면 바로 메인 진입',
      'sendWebReadyOnce로 웹뷰 브리지 준비 신호 전송',
    ] },
    { no: 'AU-02', id: 'login', name: '로그인', path: '/MobileLogin', spec: [
      '★ 아이디·비밀번호 로그인과 구글·카카오·애플 소셜 로그인 제공, 성공 시 /MobileSplash로 이동해 분기 처리',
      '★ 개발 환경(localhost)에서 test1·test3 아이디는 Cloud Function으로 커스텀 토큰을 받아 비번 없이 우회 로그인',
      '카카오 리다이렉트 복귀(?code=) 감지 시 consumeKakaoRedirectIfAny로 로그인 마무리',
      '아이디/비밀번호 찾기 링크로 /MobileFindAccount?tab=find_id·reset_pw 이동',
      '회원가입 링크로 /MobileSignup 이동, 실패 시 에러 문구 노출',
    ] },
    { no: 'AU-03', id: 'signup', name: '회원가입', path: '/MobileSignup', spec: [
      '★ 아이디·비밀번호·비밀번호확인·이름으로 이메일 회원가입(signUpWithEmailPassword)',
      '비밀번호 6자 이상 및 두 입력 일치 검증, 미충족 시 토스트 안내',
      'already-in-use 에러는 "이미 사용 중인 아이디" 토스트로 변환',
      'watchAuthState가 가입 성공을 감지하면 /MobileSetNickname으로 자동 이동',
      '처리 중에는 오버레이 스피너로 중복 제출 방지',
    ] },
    { no: 'AU-04', id: 'find-account', name: '아이디/비밀번호 찾기', path: '/MobileFindAccount', spec: [
      '★ 전화번호 SMS OTP 인증 후 가입 계정을 조회 — 탭(find_id/reset_pw)에 따라 아이디 마스킹 표시 또는 비밀번호 재설정 처리',
      '★ 테스트 번호대(01062141000~01062142000)는 OTP를 화면에 표시하는 개발모드로 동작',
      '인증번호 전송은 AuthCodeSend Cloud Function 호출, 60초 재전송 타이머 적용',
      '아이디 찾기는 이메일 로컬파트를 마스킹(첫글자+***)해 provider 라벨과 함께 표시',
      '비번 찾기에서 이메일 계정이면 재설정 메일 발송, 소셜 계정이면 해당 소셜 로그인 안내',
      '해당 전화번호로 가입된 계정이 없으면 에러 안내 후 다시 시도',
    ] },
    { no: 'AU-05', id: 'link-phone', name: '전화번호 등록/계정 연결', path: '/MobileLinkPhone', spec: [
      '★ 전화번호를 입력·연결하며, 같은 번호의 기존 사용자가 있으면 현재 계정을 그 계정에 통합(linkSocialToExistingUser/linkEmailToExistingUser)',
      '★ OTP 인증 로직은 있으나 실제 완료(handleComplete)는 인증을 생략하고 번호 형식 유효성만 확인',
      '미로그인(currentUser 없음) 시 /MobileLogin으로 강제 이동',
      '기존 계정 연결 시 primaryUid를 localStorage·UserContext에 저장하고 refreshUser 후 /MobileMain 이동',
      '신규 연결 시 initUserDoc·linkPhoneToUid 후 /ReferralInput으로 이동, "나중에 하기"는 바로 /MobileMain',
    ] },
    { no: 'AU-06', id: 'set-nickname', name: '대화명 설정', path: '/MobileSetNickname', spec: [
      '★ 최대 6자 대화명을 설정하고 role:user로 프로필을 upsert, 완료 후 /MobileSplash로 돌아가 재분기',
      '★ 형용사+명사 조합으로 중복 없는 닉네임을 자동 생성(최대 20회 시도, 실패 시 숫자 접미)',
      '수동 입력 시 500ms 디바운스로 isNicknameTaken 중복 확인(checking/ok/taken 상태)',
      '추천인 코드(선택) 입력란 제공, 입력 시 applyReferralCode 적용하되 실패해도 진행',
      'provider(소셜/이메일)를 판별해 프로필에 provider가 없을 때만 저장',
    ] },
    { no: 'AU-07', id: 'referral-input', name: '추천코드 입력', path: '/ReferralInput', spec: [
      '★ 가입 플로우 중 추천코드를 입력·적용(applyReferralCode)하는 선택 단계',
      '적용 성공 시 1.5초 뒤 /MobileSetNickname으로 이동, 실패 시 에러 문구 표시',
      '"넘어가기"로 코드 없이 /MobileSetNickname으로 이동 가능',
      '입력값은 자동 대문자 변환, 최대 8자',
      '나·추천인 각 +100P 혜택 안내 박스 표시',
    ] },
    { no: 'AU-08', id: 'seed-login', name: '시드 계정 로그인(개발 전용)', path: '/seed-login', spec: [
      '★ 개발·테스트 전용 화면 — 시드 계정 카드 클릭 시 Cloud Function 커스텀 토큰으로 signInWithCustomToken 로그인',
      '★ secret 토큰이 클라이언트에 노출되므로 테스트 후 함수 삭제 권장',
      '의뢰자 5 / 홈프로 메인 4 / 홈프로 지원자풀 5, 총 14개 시드 계정을 역할별 그리드로 제공',
      'getSeedLoginToken 함수 URL을 입력·localStorage 저장해 재방문 시 자동 입력',
      '로그인 성공 시 /MobileMain으로 이동',
    ] },
    { no: 'AU-09', id: 'terms', name: '이용약관', path: '/legal/terms', spec: [
      '★ 홈프로 서비스 이용약관 정적 문서(시행일 2026-02-08), SimpleBackLayout 뒤로가기 헤더',
      '목적·정의·회원가입·서비스내용·전문가 의무·이용요금·탈퇴·면책·분쟁해결 등 11개 조항+부칙',
      '만 14세 미만 가입 거부, 회사는 매칭 플랫폼으로 거래 당사자가 아님을 명시',
    ] },
    { no: 'AU-10', id: 'privacy', name: '개인정보처리방침', path: '/legal/privacy', spec: [
      '★ 개인정보 수집·이용·보관·파기 방침 정적 문서(시행일 2026-02-08)',
      '수집 항목: 이름/이메일/휴대전화, 소셜 식별자, 전문가 사업자등록증, 자동수집 기기·접속정보',
      '법령별 보존기간(계약·결제 5년, 분쟁 3년, 접속기록 3개월) 및 제3자 제공 예외 명시',
      'Firebase Authentication 기반 암호화 등 안전성 확보조치 기재',
    ] },
    { no: 'AU-11', id: 'location-terms', name: '위치기반서비스 이용약관', path: '/legal/location', spec: [
      '★ 위치기반서비스 이용약관 정적 문서(시행일 2026-02-08)',
      '주변 전문가 검색·서비스지역 설정·거리 기반 매칭·오더 위치 지정 등 위치서비스 내용 규정',
      'GPS/Wi-Fi/기지국 수집, 동의 철회권, 확인자료 6개월 보관, 만 14세 미만 법정대리인 동의',
      '방송통신위원회 재정·개인정보분쟁조정위원회 조정 등 분쟁 절차 안내',
    ] },
  ] },
  { key: 'main', label: '메인·설정', screens: [
    { no: 'MA-01', id: 'main', name: '모바일 메인 홈', path: '/MobileMain', spec: [
      '★ 상단 탭 5개로 화면 전환: 오더목록·나의오더현황·AI견적·초대코드·보유자산',
      '오더목록 탭은 정렬/상태/거리/기간/카테고리 5종 필터를 바텀시트로 제공하고 오더를 표(날짜·상태·서비스·지역·단가유형·요청방식)로 나열',
      '오더 상태는 접수/대기/마감/취소로 매핑하며 마감 항목은 진입 차단, 지역·단가유형·요청방식 라벨을 축약 표기',
      '보유자산 탭은 총 보유 포인트와 기간별(전체~지난3개월) 포인트 적립/사용 내역 표시',
      '초대코드 탭은 내 추천코드 복사·재발행, 초대 현황(친구 수·받은 포인트), 추천코드 입력/적용 처리',
      '★ 하단 플로팅 버튼(+ 예약접수)으로 오더 생성 이동, 당겨서 새로고침·10초 자동갱신·버전 변경 시 강제 리로드 지원',
    ] },
    { no: 'MA-02', id: 'config', name: '마이페이지(설정)', path: '/MobileConfig', spec: [
      '★ 상단 프로필 카드에서 대화명·자기소개·프로필 사진 편집(모달)과 등급 뱃지·등급 안내 바텀시트 제공',
      '비즈프로필·지갑주소 등록·전문가 리스트·커뮤니티로 이동하는 카드 메뉴 나열',
      '추천코드 복사/재발행과 초대 현황, 구독 관리(무료 체험중), 포인트/정산(보유 포인트·이번달 수익·정산 대기) 카드 표시',
      '홈프로 가이드 5종을 가로 스크롤 카드로 노출(각 /guide/N 이동)',
      '차단 관리(블랙리스트·거부 목록)와 고객지원(공지·고객센터·약관·개인정보·위치기반·버전 정보) 목록',
      '로그아웃 시 세션·프로 카테고리 초기화 후 로그인 화면으로 이동',
    ] },
    { no: 'MA-03', id: 'landing', name: 'PC 영업 랜딩', path: '/intro', spec: [
      '★ 앱 다운로드 유도용 PC 반응형 원페이지 랜딩(프로 간 하도급·외주 B2B 톤)',
      '히어로(폰 목업)·통계바(33개 카테고리/AI/5분/0원)·홍보 갤러리·프로 공감(페인포인트 3종) 섹션 구성',
      '핵심기능 4종(오더·견적, AI 견적, 오더 배정, 일정·채팅)을 브라우저 목업과 포인트 리스트로 소개',
      '이용방법 3스텝(오더 등록→견적 비교·선택→채팅 진행·완료)과 App Store·Google Play 다운로드 CTA',
      'FAQ 아코디언 5문항과 약관 링크 푸터 포함',
    ] },
    { no: 'MA-04', id: 'guide', name: '홈프로 가이드 상세', path: '/guide/:guideId', spec: [
      '★ guideId(1~5)로 가이드를 선택해 제목·색상 히어로와 단계별 타임라인 렌더링',
      '가이드 5종: 첫 견적 보내기, 리뷰 늘리는 법, 홈프로캐시 보상, 프로필 사진, 등급 시스템',
      '각 가이드는 번호가 매겨진 4단계 스텝(제목·설명, 선택적 이미지)을 세로 타임라인으로 표시',
      '존재하지 않는 guideId면 "존재하지 않는 가이드입니다" 안내 표시',
    ] },
  ] },
  { key: 'order', label: '오더·견적', screens: [
    { no: 'OD-01', id: 'order-create', name: '견적서 요청(오더 등록)', path: '/order/create · /order/create/:categoryId', spec: [
      '카테고리(아코디언 나열)를 고르면 그 아래로 orderFormConfig 기반 동적 접수폼이 펼쳐지고, worker_call 카테고리는 작업자요청 탭으로 우회 이동',
      '서비스(subGroup) 선택 카테고리는 서비스→종목 드릴다운 후에야 옵션·공간구조·건물유형·면적 등 상세필드 노출(SERVICE_FORM_MAP으로 전용 상세폼 매핑)',
      '공통 입력: 세부항목 칩(다중), 상세 요청내용(+전화먼저 체크), 현장사진 최대 4장(350px 리사이즈·JPEG 0.7 압축), Daum 우편번호 주소검색+상세주소',
      'B2B 거래조건 필드: 작업날짜(희망날짜 date), 작업시간(작업시작 시각 칩), 연락처(접수자 본인 자동+고객 실무자 선택), 단가유형(시공금액/잔금/H포인트/현장견적 등), 소개(캐시백)수수료(정액/정률+지급방법), 홈프로 선택(matchType, direct 시 지정 전화번호)',
      'validateForm: 카테고리·(subGroups면)세부항목·작업날짜·주소·요청내용 필수, direct 단가는 금액 필수',
      '"다음(입력 확인)"으로 preview 스텝 진입 → 입력 요약 표시 후 [수정하기]/[대기]/[등록하기] 3버튼',
      '★ 등록 시 createOrder 호출, orderStatus는 "접수"(정상) 또는 "대기"(메인 미노출·재접수 가능), 성공 후 sessionStorage로 나의오더현황 탭 지정하고 /MobileMain 이동',
    ] },
    { no: 'OD-02', id: 'order-list', name: '전체 오더 목록', path: '/order/list', spec: [
      'getOrdersPaginated로 20개씩 페이지네이션 조회, 하단 "더보기" 버튼으로 추가 로드',
      '★ 결제·완료·리뷰·취소 상태 및 내가 숨긴(hiddenBy) 오더는 목록에서 제외',
      '카드에 작성자·견적 보낸 프로 수(quoteCount)·카테고리·세부항목·위치·설명(2줄)·가격 표시, matchType이 "우선"이면 우선 배지',
      '카드 하단 [삭제하기](hideOrder로 나에게만 숨김)·[자세히 보기](order/detail로 이동, order·category state 전달)',
      '빈 목록·로딩 시 안내 문구, 삭제 시 토스트',
    ] },
    { no: 'OD-03', id: 'order-detail', name: '오더 상세', path: '/order/detail/:orderId', spec: [
      'order는 라우터 state 우선, 없으면 getOrder(orderId)로 Firestore 직조회, category도 state 또는 categoryId 매칭',
      '역할 판정: isOwner(createdBy===myUid) / isMatchedPro(matchedProUid===myUid) / matchType(priority·compare·direct) / isUnpriced(onsite·estimate·quote 단가는 금액 미정)',
      '정보 섹션: 제목·작성자, 업무분류 태그, 첨부사진 캐러셀, 기본정보(지역은 비당사자에게 앞 2어절만 노출), 작업일정, 단가·결제, 소개수수료, 요청방식, 요청상세',
      '연락처(접수자/고객)는 isOwner 또는 isMatchedPro에게만 공개, 활동이력 타임라인은 당사자·지원자에게만 노출',
      '★ 하단 고정 CTA가 역할·매칭방식별로 분기: 접수자=[수정/대기후수정(배정후 비활성)/취소], priority·fallback=[전화][수락하기], compare=[전화][지원하기], direct=[거절하기][수락하기]',
      '★ 수락(acceptOrder)→배정, 지원(applyToOrder), 거절(setOrderWaiting→대기)·재접수·대기후수정 등 상태전환을 addOrderLog로 기록하고 수락/지원 후 나의오더현황으로 이동',
      '홈프로 액션 전 checkPermission: 본인 오더 불가·비즈프로필 승인(approved)된 사업자만 허용, pending은 승인대기 안내',
      '★ 비교선정(compare) 접수자에게 지원 홈프로 목록+견적가 표시 → [선정]하면 selectPro로 자동 배정, 선정자에 pro_selected·나머지에 select_closed 푸시',
      '견적 바텀시트(handleQuote/handleSendQuote): 금액(0원=현장방문후결정)+제안 입력 → sendQuote·견적도착 푸시·채팅방 자동생성+시스템 견적메시지 후 채팅으로 이동',
      '접수자 "받은견적" 카드에서 [수락](acceptQuote)→채팅방 quoteStatus 갱신·프로에 quote_accepted 푸시(견적 수정은 불가)',
      '취소는 사유 선택(잘못접수/일정변경/오더수정/기타) 모달 후 updateOrderStatus로 취소+cancelReason 저장',
    ] },
    { no: 'OD-04', id: 'ai-estimate', name: 'AI 견적 분석', path: '/order/ai-estimate', spec: [
      '카테고리(그룹 아코디언)·세부항목(다중)·공간유형·면적·작업내용을 입력 후 [AI 견적 분석하기]',
      '★ getAiEstimate(Gemini) 호출, 결과 status가 success/need_info로 분기',
      'success: 예상 비용 범위(min~max)·항목별 내역 토글·예상 소요시간·Tip·산출 근거 토글·면책 문구 표시',
      'need_info: 추가로 필요한 질문 목록과 partialEstimate(대략 범위) 표시 후 다시 분석',
      '★ [실제 견적 요청하기]로 /order/create에 fromAI·카테고리·세부항목·aiEstimate state를 넘겨 실제 접수로 연결',
    ] },
    { no: 'OD-05', id: 'my-orders', name: '나의 오더현황(뒤로가기 헤더)', path: '/order/my-orders', spec: [
      'MyOrdersContent를 SimpleBackLayout(상단 뒤로가기, 하단탭 없음)으로 감싼 래퍼 화면 — /my-orders와 내용 동일, 레이아웃만 다름',
      '내가 준 일감(getOrdersByUser)+받은 일감(getOrdersByMatchedPro)+지원한 일감(getOrdersByApplicant)을 합쳐 중복제거·최신순',
      '지난오더조회 기간필터(당일~6개월+날짜범위)와 리스트/달력 뷰 토글',
      '★ 상태 필터 탭(전체/접수/대기/선정대기/배정/완료/취소)+건수, normalizeStatus로 Firestore 상태를 표시 상태로 매핑, 탭별 설명 말풍선',
      '★ 카드 상태·역할별 액션: 접수(수정/대기/취소), 대기(재접수/수정), 선정대기(지원자 보기), 배정(접수자=취소 / 배정프로=견적가 통보·작업완료·취소)',
      '★ 배정된 홈프로·비교선정 지원자는 금액미정 단가에 한해 견적가를 1회만 통보(notifyOnsitePrice/notifyApplicantPrice, 수정·재통보 불가)',
      '홈프로 취소는 사유 모달(8종, 자유취소=접수자 승인 게이트 없이 즉시 취소)+알림·채팅 시스템메시지, 오더별 채팅방 실시간 구독으로 프로별 미리보기·안읽음 표시',
    ] },
    { no: 'OD-06', id: 'my-orders-footer', name: '내 요청(하단탭 메인)', path: '/my-orders', spec: [
      '동일한 MyOrdersContent를 MainListLayout(하단 네비바 MYORDERS 탭, 뒤로가기 숨김)으로 감싼 메인 탭 진입용 화면',
      'my-orders(뒤로가기판)와 콘텐츠·로직은 완전히 같고 감싸는 레이아웃/네비게이션만 차이',
      '기간필터·리스트/달력 토글·상태탭·역할별 액션·견적가 통보·취소 모달 등 MyOrdersContent 기능을 그대로 제공',
    ] },
    { no: 'OD-07', id: 'worker-request-create', name: '작업자 요청 등록', path: '/order/worker-request/create', spec: [
      '플랫폼 면책 안내(중개만 제공, 계약·대금·안전 책임은 당사자) 고지 배너',
      '작업 카테고리 4군(작업내용/전문작업/작업인력/장비·특수)에서 1개 선택',
      '작업내용·현장 상세설명, 필요 인원, 픽업위치(선택)+작업위치 주소, 작업날짜(긴급/오늘/내일/날짜지정), 작업시간(구간 프리셋+시간 직접설정), 인건비 입력',
      '★ 필수검증(카테고리·작업내용·작업주소) 후 homepro_worker_requests 컬렉션에 status "접수"로 addDoc, 등록 후 뒤로가기',
    ] },
    { no: 'OD-08', id: 'worker-request-detail', name: '작업자 요청 상세', path: '/order/worker-request/detail/:requestId', spec: [
      'homepro_worker_requests/:requestId를 onSnapshot 실시간 구독, 카테고리·주소·일정·인원·인건비 등 정보 카드 표시',
      '★ 작성자(isOwner)에게는 받은 응답(applicants) 목록과 각 응답자별 [채팅 시작] 노출',
      '★ 타인은 [응답 등록](applicants에 arrayUnion, 이미 응답 시 안내) + 작성자에게 [채팅 문의]',
      '채팅은 createChatRoom({type:"worker_request"})로 생성 후 /chat/:roomId 이동',
    ] },
  ] },
  { key: 'chat', label: '채팅·계약', screens: [
    { no: 'CH-01', id: 'chat-list', name: '채팅 목록', path: '/MobileChat', spec: [
      '일반/오픈채팅 2탭 구성, 각 탭 방 개수 배지 표시',
      '일반 탭은 카테고리 칩(전체·오더·기술전수·자재장비·기타)으로, roomType 기준 분류 필터',
      '오픈 탭은 참여 여부 무관 전체 공개방 둘러보기, 카테고리 칩(전체·오더·인력·기술교육·매매양도·자재장비) 필터',
      '★ 일반 방은 1차 탭 시 포커스, 재탭 시 채팅방 진입 / 오픈 방은 미참여 시 joinOpenRoom 후 입장',
      '방마다 안읽음 수 배지, 마지막 메시지/시각, 오더 연동 방은 종목 태그 클릭으로 오더 상세 이동',
      '오픈채팅 신규 생성 없음 — 운영 개설방 참여만 가능',
    ] },
    { no: 'CH-02', id: 'chat-detail', name: '채팅방', path: '/chat/:roomId', spec: [
      '★ 견적 연동 방은 견적 카드(가격·메시지·프로 프로필·등급)를 시스템 메시지로 표시, 상태 pending/rejected/cancelled면 입력창 잠금',
      '★ 수락·작업완료·취소 등 상태 변경은 채팅이 아닌 오더 상세/나의오더현황에서 처리하도록 안내 바로 유도',
      '일정 공유 모달: 미니 캘린더로 기간 선택·여러 건 추가, 바(라인)로 렌더링하고 homepro_schedules(source:chat)에 저장 후 채팅에 미니캘린더 뷰로 공유',
      '메시지 타입별 렌더링(텍스트·이미지·파일·일정), 롱프레스 메뉴로 수정/삭제하되 읽은 메시지(readBy)는 삭제 불가',
      '읽음 표시(안읽음 1 배지)·상대방 입력중 타이핑 표시·메시지 검색(하이라이트·결과 이동) 지원',
      '결제/작업완료/리뷰 바텀시트, 상단 게시글(메모) 배너, 거부 등록·채팅방 나가기, 상태 변경 시 상대방 푸시 알림',
    ] },
    { no: 'CH-03', id: 'chat-memo', name: '채팅방 게시글', path: '/chat/:roomId/memo', spec: [
      '채팅방 상단에 고정할 게시글(공지·작업 지시·현장 안내)을 작성하는 화면',
      '기존 메모 유무에 따라 게시글 등록/수정 모드 전환, 내용 없으면 저장 비활성',
      '저장은 updateMemo, 기존 게시글이 있으면 하단에 게시글 삭제 버튼 노출',
      '저장/삭제 후 이전 화면으로 복귀',
    ] },
    { no: 'CH-04', id: 'open-chat-create', name: '오픈채팅 개설', path: '/chat/open/create', spec: [
      '채팅방 이름(필수·최대 30자)·카테고리·방 소개를 입력해 공개 채팅방 개설',
      '카테고리 칩 선택(오더·인력·기술교육·매매양도·자재장비)',
      '★ 개설 시 누구나 참여 가능한 공개방 생성, 개설자가 방장이 되어 개설 후 해당 방으로 이동',
      '이름 미입력 등 검증 실패 시 토스트 안내',
    ] },
    { no: 'CH-05', id: 'contract', name: '계약', path: '/MobileContract', spec: [
      '전체/진행중/완료 상태 탭 구성',
      '계약 내역이 없는 빈 상태 화면 (목록 로직 미구현)',
      '프로/의뢰인 모드(appMode)에 따라 안내 문구 분기',
    ] },
  ] },
  { key: 'pro', label: '프로·카테고리', screens: [
    { no: 'PR-01', id: 'biz-profile', name: '비즈프로필', path: '/biz-profile', spec: [
      '내 프로필 요약(사진/상호/등급 뱃지/한줄소개/지역)과 등급 진행바를 표시',
      '★ 활동 통계 4열: 누적 포인트·견적 보낸 수·고용 수·리뷰 수(오더 quotes 및 matchedProUid 집계)',
      '본인일 때만 정산 계좌(은행/계좌번호/예금주) 입력·저장, 소개비·정산금 입금용',
      '등록한 전문분야 카드 목록(상태 뱃지·전문분야칩·자격증·지역), 카테고리 상세로 이동',
      'location.state.viewUid로 타인 프로필 조회 시 승인된 전문분야만 노출',
      '★ 타인 프로필에서 블랙리스트 신고(사유 입력) 가능',
    ] },
    { no: 'PR-02', id: 'pro-list', name: '전문가 리스트', path: '/pro/list', spec: [
      'status가 approved인 프로 전체 조회, 본인 제외하고 users 프로필과 매칭해 표시',
      '카테고리 그룹(CATEGORY_GROUPS) 칩으로 분야 필터링',
      '★ 내 지역 좌표 기준 거리(10/20/30/50/100km) 바텀시트 필터(Haversine 계산)',
      '즐겨찾기 별표 토글(users/{uid}/favorites 서브컬렉션 저장)',
      '카드 클릭 시 해당 프로 비즈프로필(viewUid 전달)로 이동',
    ] },
    { no: 'PR-03', id: 'pro-category-register', name: '전문분야 등록', path: '/pro/register-category', spec: [
      '★ 2스텝 위저드: 스텝1 분야 선택(그룹별 아이콘 그리드, 이미 등록분야는 비활성), 스텝2 상세 정보',
      '세부분야 복수 선택 칩 + PRO_DETAIL_FIELDS 기반 카테고리별 동적 입력(text/number/textarea/chips)',
      '자격증 필드는 자격증명+사진 페어 카드로 여러 건 추가/삭제',
      '경력(년)·한줄소개(최대100자)·활동지역(RegionSelectModal) 입력',
      '★ 사업자등록증 이미지 필수 첨부, 활동 사진 최대 10장 첨부',
      '제출 시 라이선스·활동사진 업로드 후 registerProCategory 호출(경력·소개 필수)',
    ] },
    { no: 'PR-04', id: 'pro-category-list', name: '업무분야 관리', path: '/pro/categories', spec: [
      'proCategoriesAtom에 등록된 내 업무분야를 아이콘·이름·승인완료 상태로 리스트 표시',
      '각 행 클릭 시 해당 카테고리 상세(/pro/category-detail)로 이동',
      '등록 분야 없으면 빈 상태 안내, 하단 분야 추가 등록 버튼으로 등록 페이지 이동',
    ] },
    { no: 'PR-05', id: 'pro-category-detail', name: '전문분야 상세', path: '/pro/category-detail/:categoryId', spec: [
      '활동 사진 가로 슬라이더(카운터 표시)와 카테고리명·검수 상태 뱃지 표시',
      '소개·기본정보(경력/지역/전문분야)·PRO_DETAIL_FIELDS 동적 렌더링',
      '제출 서류(사업자등록증·자격증)와 검수완료/검수중 상태, 신청일·승인일 표시',
      '★ 본인일 때만 프로필 수정·업무분야 삭제(deleteProCategory) 버튼 노출',
      'viewUid state로 타인 상세 조회 지원(수정/삭제 숨김)',
    ] },
    { no: 'PR-06', id: 'pro-category-edit', name: '전문분야 수정', path: '/pro/category-edit/:categoryId', spec: [
      'getProCategoryDoc으로 기존 세부분야·경력·소개·지역·자격증·서류·사진을 불러와 폼에 복원',
      '세부분야 칩·동적 필드·자격증 페어·경력·소개(100자)·활동지역 수정',
      '★ 기존 사업자등록증/활동사진 유지 또는 교체, 활동사진 기존+신규 합쳐 최대 10장',
      '저장 시 registerProCategory로 덮어쓰기(경력·소개·라이선스 필수 검증)',
    ] },
    { no: 'PR-07', id: 'category-pro-list', name: '카테고리별 전문가 목록', path: '/category/:categoryId', spec: [
      '★ 사용자 선택 지역 기준 getProsByCategory로 해당 카테고리 프로 조회',
      '카테고리 헤더(아이콘/이름/설명)와 전문가 수, 경력순 정렬 옵션 표시',
      '프로별 서비스 카드(사진영역·소개·경력·지역·세부분야 태그·상세보기)',
      '카드 클릭 시 서비스 상세(/service)로 service·category state 전달',
      '★ 헤더 요청하기 버튼으로 오더 생성(/order/create/:categoryId) 이동',
    ] },
    { no: 'PR-08', id: 'service-detail', name: '서비스 상세', path: '/service/:categoryId/:serviceId', spec: [
      'location.state의 service·category로 렌더링(직접 진입 시 정보 없음 안내)',
      '히어로 사진·전문가 프로필(이름/지역/경력/평점)·사업자 인증 뱃지 표시',
      '서비스 소개·태그, 가격 안내(상세 견적은 요청 후 안내), 전문 분야, 리뷰(빈 상태)',
      '★ 하단 고정 CTA: 채팅 시작(createChatRoom)·전화·서비스 요청하기(오더 생성)',
    ] },
  ] },
  { key: 'market', label: '마켓·부가', screens: [
    { no: 'MK-01', id: 'marketplace', name: '도급·양도·매매 목록', path: '/marketplace', spec: [
      'homepro_marketplace 컬렉션을 createdAt 내림차순 실시간 구독(onSnapshot)해 카드 리스트로 표시',
      '거래유형 8종(시공도급·작업도급·사업권양도·물품매매·장비매매·업체인수양도·설치도급·공사도급) + 전체 칩 필터',
      '카드에 거래유형 뱃지·등록일·제목·지역·계약방식·사진수·금액·설명 80자 미리보기 표시',
      '★유료구독 게이트 안내(현재 isSubscriber는 || true 임시 통과 placeholder)',
      '+ 등록 FAB로 /marketplace/create 이동, 카드 클릭 시 상세로 이동',
    ] },
    { no: 'MK-02', id: 'marketplace-create', name: '도급·양도·매매 등록', path: '/marketplace/create', spec: [
      '거래유형·회원유형(개인/사업자/법인)·계약방식(도급/일괄매매/부분양도/협의) 칩 선택',
      '업체명·담당자·연락처·지역·제목·금액(협의 시 공란)·상세내용·사진 최대 4장(압축 후 Storage 업로드) 입력',
      '플랫폼 면책 안내 + 등록 전 필수 안내 5항 + 금지 등록 항목 5항(위반 시 삭제·정지·법적조치) 고지',
      '거래유형·회원유형·제목·상세내용 필수 검증 후 homepro_marketplace에 status:active로 저장',
      '★유료구독 비회원이면 게이트 화면(구독신청 → /subscription)만 노출하고 폼 차단(현재 임시 통과)',
    ] },
    { no: 'MK-03', id: 'marketplace-detail', name: '도급·양도·매매 상세', path: '/marketplace/:marketplaceId', spec: [
      'homepro_marketplace 문서를 onSnapshot 실시간 구독, 없으면 안내 표시',
      '사진 슬라이드(썸네일 전환·카운터) + 거래정보(회원유형·계약방식·지역·업체명·담당자·연락처) + 상세내용 표시',
      '거래 시 주의사항 면책 안내 노출',
      '★작성자 본인이면 게시글 삭제(deleteDoc), 타인이면 채팅 문의(createChatRoom type:marketplace → /chat)',
    ] },
    { no: 'MK-04', id: 'training', name: '기술전수교육 목록', path: '/training', spec: [
      'homepro_trainings 컬렉션을 createdAt 내림차순 실시간 구독해 카드 리스트로 표시',
      '카드에 상태 뱃지(모집중/마감)·제목·강사·설명·기간·모집인원·지역·가격(무료/원) 표시',
      '헤더에 사용자 지역명(USERINFO.address_name) 노출, footerType training',
      '+ 교육 등록 FAB로 /training/create 이동, 카드 클릭 시 상세로 이동',
    ] },
    { no: 'MK-05', id: 'training-create', name: '기술전수교육 등록', path: '/training/create', spec: [
      '교육제목·기술분야·상세내용·강사명(제목·내용·강사 필수) 입력',
      '교육방식 복수선택(현장/이론/실습), 교육기간(시작·종료일)·교육시간·모집인원 입력',
      '교육비용 무료/유료/협의 선택, 유료 시 금액 입력창 노출',
      '교육장소는 RegionSelectModal로 시도·구 선택, 연락처 입력',
      '플랫폼 면책 안내 고지 후 homepro_trainings에 status:모집중으로 저장',
    ] },
    { no: 'MK-06', id: 'training-detail', name: '기술전수교육 상세', path: '/training/:id', spec: [
      'homepro_trainings 문서를 getDoc 단건 조회해 상태·분야·제목·강사·기간·시간·인원·지역 표시',
      '교육방식 칩·교육내용·비용(무료/협의/원)·연락처·등록일 표시',
      '★하단바 전화 문의(연락처 8자리↑ 숫자면 tel: 링크) + 채팅 문의(createChatRoom trainingId → /chat)',
      '본인 등록 교육이면 채팅 불가 토스트 안내',
    ] },
    { no: 'MK-07', id: 'supplies', name: '자재·장비 업체 목록', path: '/supplies', spec: [
      'homepro_supplies 컬렉션을 createdAt 내림차순 실시간 구독해 업체 카드 리스트로 표시',
      '카드에 업체명·소개·연락처·영업시간·지역·배송가능 뱃지 표시',
      '헤더에 사용자 지역명 노출, footerType supplies',
      '+ 업체 등록 FAB로 /supplies/create 이동, 카드 클릭 시 상세로 이동',
    ] },
    { no: 'MK-08', id: 'supplies-create', name: '자재·장비 업체 등록', path: '/supplies/create', spec: [
      '업체명·소개·지역(RegionSelectModal)·연락처 필수 입력 검증',
      '영업시간 입력, 배송 가능 여부 토글 스위치',
      '취급 품목을 줄바꿈 구분 텍스트로 입력 → 배열로 파싱 저장',
      'homepro_supplies에 location(시도 구)·region·items 배열 등으로 저장 후 뒤로가기',
    ] },
    { no: 'MK-09', id: 'supplies-detail', name: '자재·장비 업체 상세', path: '/supplies/:id', spec: [
      'homepro_supplies 문서를 getDoc 단건 조회해 업체명·배송가능·연락처·영업시간·지역 표시',
      '업체 소개 + 취급 품목 칩 리스트 + 등록일 표시',
      '★하단바 전화 문의(phone tel: 링크) + 채팅 문의(createChatRoom supplyId → /chat)',
      '본인 등록 업체면 채팅 불가 토스트 안내',
    ] },
    { no: 'MK-10', id: 'subscription', name: '월 구독 신청', path: '/subscription', spec: [
      '홈프로 월 구독(월 16,500원, 부가세 포함) 혜택 안내(도급 게시판·교육 등록·프리미엄 알림)',
      '결제수단 카드/포인트/포인트+카드 혼합 선택, 보유 포인트 표시',
      '★포인트 결제 시 잔액 검증 후 PointService.applyPointPayment 차감, 혼합은 포인트 우선차감+카드 차액(카드 모듈은 연동 예정 placeholder)',
      '월 구독료는 point_rules(monthlySubscriptionPoint) 정책값 사용, 없으면 16500 기본',
      'homepro_subscriptions에 status:active 기록 후 refreshUser·뒤로가기',
    ] },
  ] },
  { key: 'community', label: '커뮤니티·지원', screens: [
    { no: 'CM-01', id: 'community', name: '커뮤니티', path: '/community', spec: [
      '자유게시판 / 이벤트·공지 2개 탭으로 게시글 목록을 전환한다.',
      'getPosts(type)로 탭별 글을 조회하며, 공지 탭이 비어있으면 기본 공지 3건을 노출한다.',
      '★ 자유게시판 글에만 좋아요·댓글 수와 작성자명을 표시하고, 하단 게시글 쓰기 버튼도 자유 탭에서만 노출한다.',
      '게시글 카드 클릭 시 /community/:postId 상세로 이동한다(기본 공지는 이동 없음).',
    ] },
    { no: 'CM-02', id: 'community-write', name: '커뮤니티 글쓰기', path: '/community/write', spec: [
      '제목·내용 입력과 이미지 최대 5장 첨부(미리보기·개별 삭제)를 지원한다.',
      '★ 이미지를 임시 postId 경로로 업로드한 뒤 type=free 글로 createPost 저장한다.',
      '제목·내용이 모두 채워져야 등록 버튼이 활성화된다.',
      '등록 성공 시 /community로 replace 이동, 실패 시 재시도 알림을 띄운다.',
    ] },
    { no: 'CM-03', id: 'community-detail', name: '커뮤니티 상세', path: '/community/:postId', spec: [
      '게시글 본문·이미지·작성자·유형(자유/이벤트·공지)을 표시한다.',
      '★ 좋아요 토글(하트)로 즉시 반영하며 checkLiked로 초기 상태를 조회한다.',
      '댓글은 parentId 기준 원댓글·대댓글 계층으로 렌더링한다.',
      '답글 버튼으로 대상 지정 후 입력, Enter 전송하면 목록을 새로고침한다.',
      '게시글이 없으면 뒤로 이동 처리한다.',
    ] },
    { no: 'CM-04', id: 'notice', name: '공지사항', path: '/notice', spec: [
      'Firestore notices 컬렉션을 createdAt 내림차순으로 조회한다.',
      '★ 각 항목을 아코디언으로 펼쳐 본문(content)을 확인한다.',
      'badge 값(이벤트/안내 등)에 따라 뱃지 색상을 다르게 표시한다.',
      '데이터가 없으면 등록된 공지사항이 없음 안내를 노출한다.',
    ] },
    { no: 'CM-05', id: 'support', name: '고객센터', path: '/support', spec: [
      '전화(1588-0000)·이메일·카카오톡 문의 연락처를 운영시간과 함께 안내한다.',
      '★ 하드코딩된 FAQ 6문항을 아코디언으로 펼쳐 답변을 확인한다.',
      'FAQ는 서비스 소개·전문가 등록·견적·결제·불만·회원탈퇴 주제를 다룬다.',
    ] },
  ] },
  { key: 'my', label: '마이·기타', screens: [
    { no: 'MY-01', id: 'wallet', name: '지갑주소 등록', path: '/mypage/wallet', spec: [
      '포인트의 토큰화 전환 대비 지갑주소를 미리 등록하는 화면(시트8 대비)',
      'users 문서의 walletAddress·walletUpdatedAt를 조회해 현재 등록 주소와 마지막 업데이트 시각 표시',
      '★ 입력값 형식 검증: EVM 0x+40hex 또는 영숫자 26~64자만 허용, 미충족 시 저장 차단',
      'PointService.setWalletAddress로 저장, 빈 값 저장 시 주소 삭제(null)로 처리',
      '동일 주소면 변경없음 토스트, 저장/삭제/실패는 토스트로 안내',
      '본인 소유·복구불가·변경 시 이전 주소 즉시 비활성화 주의 안내 노출',
    ] },
    { no: 'MY-02', id: 'blocks', name: '거부 목록', path: '/mypage/blocks', spec: [
      'BlockService.getMyBlocks로 내가 거부 등록한 사용자 목록을 조회해 표시',
      '항목마다 상대 UID·거부 사유(reason)·등록일(createdAt) 노출',
      '★ 해제 버튼: confirm 후 unblockUser 호출하고 목록에서 즉시 제거',
      '거부 대상이 없으면 안내 문구, 로딩 중 문구 분기',
    ] },
    { no: 'MY-03', id: 'blacklist', name: '블랙리스트', path: '/mypage/blacklist', spec: [
      'BlacklistService.getMyBlacklist로 내 블랙리스트를 조회',
      '★ targetUid로 users 문서를 조회해 nickname/name으로 실이름 보강(enrich) 후 표시',
      '항목마다 상대 이름·사유(reason)·등록일 노출',
      '해제 버튼: confirm 후 removeFromBlacklist 호출하고 목록에서 즉시 제거',
      '대상 없음/로딩 중 문구 분기',
    ] },
    { no: 'MY-04', id: 'calendar', name: '나의 일정', path: '/calendar', spec: [
      'homepro_schedules에서 내 uid·해당 월(date >= 01, <= 31) 일정을 조회, source==="chat" 일정은 제외',
      '★ groupId로 묶인 일정을 startDate~endDate 기간 바(라인)로 합쳐 주별 그리드에 렌더, 레인 배분으로 겹침 처리',
      '월 이동(이전/다음)·오늘 버튼, 2026년 공휴일 하드코딩 표기 및 일/토/공휴일 색상 구분',
      '날짜 선택 후 FAB로 /calendar/create 이동(선택 날짜 state 전달)',
    ] },
    { no: 'MY-05', id: 'schedule-create', name: '일정 등록', path: '/calendar/create', spec: [
      '★ 미니 캘린더에서 시작일→종료일 2탭으로 기간 선택(start/end/done 단계, 역순 선택 시 자동 보정)',
      '작업 내용 입력 후 "일정 추가하고 계속 만들기"로 여러 건을 리스트에 누적, 바로 미니 캘린더 바로 표시',
      '완료 시 기간 내 날짜를 일자별 문서로 분해해 homepro_schedules에 저장, 다중일이면 groupId 부여',
      '누적된 바 클릭 시 해당 일정 리스트에서 제거',
      '하단 버튼은 건수에 따라 "완료"/"N건 일정 등록"으로 표기',
    ] },
    { no: 'MY-06', id: 'search', name: '통합 검색', path: '/search', spec: [
      '★ CATEGORIES를 대상으로 name·shortName·description·subcategories를 부분일치 검색',
      '결과를 전체/카테고리/지역/금액/기타 탭으로 분류(지역·금액·인기검색어 데이터는 현재 빈 배열, Firestore 연동 예정)',
      '최근 검색어는 localStorage(homepro_recent_searches)에 최대 10개 저장·개별/전체 삭제',
      '기타 탭은 서브카테고리 매칭 결과, 카테고리/기타 결과 클릭 시 /category/:id 이동',
      '입력 전엔 최근·인기 검색어, 검색 후엔 탭+결과, 결과 없으면 빈 상태 문구',
    ] },
    { no: 'MY-07', id: 'referral-friends', name: '초대한 친구', path: '/referral/friends', spec: [
      '★ users 컬렉션에서 referredBy == 내 uid인 사용자를 조회해 내가 초대한 친구 목록 구성',
      '가입일(createdAt) 최신순 정렬, 상단에 초대 친구 수 요약',
      '항목마다 프로필이미지(profileImage/photoURL)·이름(nickname/name)·가입일 표시',
      '친구 없음/로딩 중 문구 분기',
    ] },
    { no: 'MY-08', id: 'referral-points', name: '포인트 내역', path: '/referral/points', spec: [
      'homepro_cash에서 내 uid 포인트 이력을 최신순 조회, users의 referralPoints(보유)·totalEarnedPoints(누적) 표시',
      '★ 활성 포인트 규칙(getAllPointRules)을 POINT_RULE_ORDER 순으로 가로 스크롤 카드(적립 방법)로 안내',
      '등급 시스템: gradeUtils의 calcGrade·GradeProgressBar로 누적 포인트 기준 현재 등급/진행도 표시(settings/grade_rules)',
      '이력 항목은 reason·날짜와 type(earn:+/use:-)에 따른 부호·색상으로 금액 표기',
      '규칙 키별 아이콘/배경색 매핑(RULE_STYLE), 구 review_like_* → community_like_* 호환 포함',
    ] },
  ] },
  { key: 'admin', label: '관리자', screens: [
    { no: 'AD-01', id: 'admin-login', name: '관리자 로그인', path: '/admin/login', spec: [
      'admin 컬렉션에서 loginId 조회 후 password 평문 대조로 인증',
      '★ 성공 시 localStorage adminSession(id·loginId·name·rank)에 세션 저장 후 /admin 이동',
      '아이디·비밀번호 미입력, 미존재 계정, 비번 불일치별 오류 메시지 분기',
      '카드형 중앙 정렬 로그인 폼 단일 화면',
    ] },
    { no: 'AD-02', id: 'admin-dashboard', name: '관리자 대시보드', path: '/admin', spec: [
      '★ 회원·매칭·채팅·광고·포인트·정산·공지·매출 8개 그룹 통계 카드를 Firestore 전수 집계로 표시',
      '카드 클릭 시 해당 필터 라우트로 이동(예 매칭 요청중/완료 등)',
      '회원 가입·매칭 건수·매출 3개 추이 차트(recharts, 이번달 일별)',
      '최근 가입 회원 5건·최근 매칭 5건 테이블',
      '전화번호 인증 회원만 카운트, orderStatus 한글→영문 상태 정규화',
    ] },
    { no: 'AD-03', id: 'admin-users', name: '회원 관리', path: '/admin/users', spec: [
      '전체/일반(general)/사업자(pro) 필터별 회원 목록, 이름·전화·이메일 검색, 20개 페이지네이션',
      '★ 행 클릭 시 상세 모달: 기본정보·주문/매칭·채팅·포인트·정산·커뮤니티·프로정보 탭(정산·프로 탭은 프로만)',
      '전화번호 미인증 유령 문서 제외, 상태 pending 시 승인/거절 처리',
      '회원 삭제 시 phones·users_by_phone 연결 문서 동시 삭제',
      '모달에서 비밀번호 변경, 포인트 잔액 자동 계산',
    ] },
    { no: 'AD-04', id: 'admin-pro-approval', name: '프로 승인관리', path: '/admin/pro-approval', spec: [
      '대기중/승인완료/반려 탭(건수 표시), 프로 이름·카테고리 검색, 20개 페이지네이션',
      '★ 승인/반려 처리 시 homepro_pros 상태 갱신 + notifications에 푸시 알림 문서 생성',
      '반려는 사유 입력 필수, 반려 건은 재승인 가능',
      '상세 모달: 프로/등록 정보, 사업자등록증·활동사진, detail 추가정보 표시',
    ] },
    { no: 'AD-05', id: 'admin-matching', name: '매칭 관리', path: '/admin/matching', spec: [
      '전체/요청중/매칭완료/진행중/완료/취소 상태 필터, 고객명·대화명·프로명 검색, 20개 페이지네이션',
      '★ 행 인라인 select로 주문 상태 즉시 변경(homepro_orders status 갱신)',
      'orderStatus 한글→영문 정규화, createdBy로 고객 실명 매핑',
      '상세 모달: 주문·고객·프로 정보, 세부분류·주소·공간유형·일정·매칭방식 표시',
    ] },
    { no: 'AD-06', id: 'admin-chat', name: '채팅 관리', path: '/admin/chat', spec: [
      '전체/활성/관심(flagged)/종료 필터로 chatRooms 목록, 마지막 메시지순 정렬',
      '★ 행 클릭 시 상세 모달에서 messages 서브컬렉션 최근 50건 열람',
      'quoteStatus·workStatus·paymentStatus 조합으로 대기/수락/결제완료/완료/거절/취소 상태 표기',
      '채팅방 삭제 기능, 참여자명(participantNames) 표시',
    ] },
    { no: 'AD-07', id: 'admin-ads', name: '광고 관리', path: '/admin/ads', spec: [
      '상단/중간/설정/팝업 배너 위치별 필터, ads 컬렉션 최신순',
      '★ 광고 등록/수정 모달: 제목·이미지URL·링크URL·위치·기간·활성여부',
      '종료일 경과 시 만료, active 여부로 활성/비활성 상태 자동 판별',
      '클릭수 표시, 광고 삭제 기능',
    ] },
    { no: 'AD-08', id: 'admin-points', name: '포인트 관리', path: '/admin/points', spec: [
      '포인트 내역 / 규칙 설정 메인 탭 분리',
      '★ 내역 탭: 전체/적립/사용/환불 필터, 회원명·전화 검색, 관리자 수동 지급/차감 등록',
      '규칙 탭: settings/point_rules 활동별 지급액·활성 토글 편집·저장',
      '★ 토큰화 정책(시트8): 네트워크 수수료율·추천인 보상률·스왑 비율·월 구독료 _policy에 저장',
      '금액은 유형별 부호(+/-)로 표시, 20개 페이지네이션',
    ] },
    { no: 'AD-09', id: 'admin-notice', name: '공지 관리', path: '/admin/notice', spec: [
      '전체/고정/일반 필터, 고정 공지 상단 우선 정렬',
      '★ 공지 작성/수정 모달: 분류(공지·이벤트·안내)·제목·내용·상단고정',
      '별표 클릭으로 고정(pinned) 토글, 공지 삭제 기능',
      'notices 컬렉션 최신순 조회',
    ] },
    { no: 'AD-10', id: 'admin-settlement', name: '정산 관리', path: '/admin/settlement', spec: [
      '전체/대기/승인/완료/거절 상태 필터, 프로명·UID·정산ID 검색, 20개 페이지네이션',
      '★ 총 정산완료·대기금액·이번달 정산·총건수 요약 카드',
      '행 인라인 select로 상태 변경(완료 시 completedAt 기록)',
      '정산 등록 모달: 프로UID·프로명·금액·정산방법(계좌이체/카드/기타)·비고, 상세 모달 열람',
    ] },
    { no: 'AD-11', id: 'admin-updates', name: '앱 업데이트 관리', path: '/admin/updates', spec: [
      '★ 버전·업데이트 내용 등록 시 app_updates 컬렉션에 저장(자동 새로고침 트리거용)',
      '등록된 버전 목록을 최신순 표시, date 자동 기록',
      '버전 삭제 기능',
    ] },
    { no: 'AD-12', id: 'admin-settings', name: '설정', path: '/admin/settings', spec: [
      '앱 푸시알림·정관/약관·AI·테스트데이터 4개 섹션(라우트 파라미터로 전환)',
      '푸시알림 섹션: 주문·채팅·공지·마케팅 토글 저장, 관리자 비밀번호 변경',
      '약관 섹션: 이용약관·개인정보·위치기반 저장 + 회사 정보 편집',
      '★ AI 섹션: AI 견적 활성화·모델 선택·최대토큰·시스템 프롬프트를 settings/ai에 저장',
      '★ 테스트 섹션: 오더 20개·프로 5명 시딩 및 isTest 데이터 일괄 삭제',
    ] },
  ] },
]
